Arrays classes and objects
mrgumball1/Homeworks pull request #3
Opened 2023-05-16 20:08 UTC by mrgumball1

Homework

2023-06-12 12:46 UTC, janistumpelis requested changes
Paldies, pa lielam ir ok, tikai ņem ārā tās main metodes no klasēm, no kurām taisi objektus.

2023-06-12 12:46 UTC, janistumpelis commented on Homeworks/src/main/java/io/codelex/classesandobjects/practice/Exercise4/Movie.java
> +    public static void main(String[] args) {
Iekš klases no kuras veidojam objektus mēs main metodi iekšā neliec, iznes ārā citā klasē.

2023-06-12 12:46 UTC, janistumpelis commented on Homeworks/src/main/java/io/codelex/classesandobjects/practice/Account.java
> +    public static void main(String[] args) {
Iekš klases no kuras veidojam objektus mēs main metodi iekšā neliec, iznes ārā citā klasē.

2023-06-12 12:46 UTC, janistumpelis commented on Homeworks/src/main/java/io/codelex/classesandobjects/practice/Exercise8/SavingsAccount.java
> +    public static void main(String[] args) {
Tas pats - iznes main metodi ārā citā klasē.

2023-06-12 12:46 UTC, janistumpelis commented on Homeworks/src/main/java/io/codelex/classesandobjects/practice/swapPoints.java
> +public class swapPoints {
Klase ar mazo burtu.

2023-06-13 21:02 UTC, mrgumball1 commented
> Paldies, pa lielam ir ok, tikai ņem ārā tās main metodes no klasēm, no kurām taisi objektus.

Everything done will fix this mistake in all upcoming homeworks

2023-07-02 05:01 UTC, janistumpelis approved these changes

2023-07-02 10:04 UTC, merged